### PR TITLE
[WIP] Respect cron locks when running crons

### LINKED ISSUE #27: wp cron event run --due-now doesn't respect doing_cron transient
I use `wp cron event run --due-now` as my production cron. Every 5 minutes. But it's a heavy cron.  Sometimes it takes more then 5 minutes. When that happens some events get executed twice. Mostly sending emails.

I would suggest a `--no-doubles` flag or something like that to prevent the cron from doing hooks twice.

When the flag is set, wp-cli should check for the `doing_cron` transient like core does. And set it if it's starting. Like core does.

[Relevant core code](https://github.com/WordPress/WordPress/blob/4.9.6/wp-cron.php#L78)

**Why is it doing things twice**

At the start of a cron all tasks are gathered with [_get_cron_array](https://github.com/WordPress/WordPress/blob/4.9.6/wp-includes/cron.php#L477), events get deleted once the start. And the remaing cron array is still executed. And still in the DB list So after 5 minutes the new cron get also does a [_get_cron_array](https://github.com/WordPress/WordPress/blob/4.9.6/wp-includes/cron.php#L477) and will get all events that the first cron also is still handling (and deleting as it goes).

### PR DESCRIPTION
**Pull request by schlessera**
Fixes #27

### CODE REVIEW

**Comment by schlessera** [comment]
This does not yet work as expected and needs further investigation.

**Comment by calind** [comment]
Hi, any update on this one? Is there anything I do to help?

**Comment by khromov** [comment]
Any way to merge this?

**Comment by maxledoux** [comment]
+1 for getting this done, please. I am seeing crons getting run twice because `--due-now` occasionally takes longer than 5 minutes. (I run `wp cron event run --due-now` every 5 minutes.)

**Comment by danielbachhuber** [comment]
Proceeding with https://github.com/wp-cli/wp-cli/issues/5594 for this repository. I've captured this PR to https://gist.github.com/danielbachhuber/e76c5c5e1479c385863cc86f5f21eb87 in case this PR is auto-closed or broken in some way.

**Pull request closed without merging**
