### PR TITLE
When due-now get events from wp_get_ready_cron_jobs

### PR DESCRIPTION
**Pull request by josedumas**

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@josedumas Did the tests pass locally?

**Comment by josedumas** [comment]
Hi @danielbachhuber 

I did the phpcs test, which didn't give me any errors, but not the other tests.

Fails performing the test: run-behat-tests I don't know how to perform these tests, honestly

I am going to have to learn more about this then, and I think that what I can contribute at this moment is beyond my knowledge.

I close the PR until I learn how to perform these tasks.

**Comment by danielbachhuber** [comment]
> Fails performing the test: run-behat-tests I don't know how to perform these tests, honestly
> 
> I am going to have to learn more about this then, and I think that what I can contribute at this moment is beyond my knowledge.
> 
> I close the PR until I learn how to perform these tasks

@josedumas No worries! When you're ready to explore further, [here's the feature test documentation](https://make.wordpress.org/cli/handbook/contributions/pull-requests/#functional-tests). The [document is editable](https://github.com/wp-cli/handbook/blob/main/pull-requests.md) if you find any improvements that could be made.

**Comment by danielbachhuber** [comment]
> I will read the documentation and try to do the tasks correctly and as detailed there. I'm learning a lot about how to collaborate on an open source project. Thanks for the help.

@josedumas Sounds great! Hopefully the knowledge will be helpful in the future, too 😊

> But first, I think I should stop and think if for this small improvement that nobody needs (just me :)) it is convenient to change any of the code and it is not worth being modified. Applying the rule: "If it works, don't touch it". I have observed that this code (Cron_Event_Command.php) has not been modified for more than 2 years and I honestly believe that my request is not claimed/needed by anyone. What do you think about it?

I think it's a reasonable assumption that `--due-now` should call `wp_get_ready_cron_jobs()`. We try to emulate WordPress core's behavior as much as possible.

**Pull request closed without merging**
